version: '2'
services:
 ghost: 
  build: ./ghost 
  container_name: ghost 
  ports:
   - "8999"
  volumes:
   - "./logs:/tmp"
  restart: always
 
 nginx:
  build: ./nginx
  container_name: nginx
  ports:
   - "80:80"
  volumes:
   - "/etc/nginx:/etc/nginx" 
  restart: always
